insert into public.alarms (machine_id, alarm_code, description, cause, status, created_at) select id, $$ERR-CABLE-01$$, $$Charging gun fails to lock with the CCS2 connector$$, $$Lock actuator jammed, cable damaged$$, $$Open$$, now() - make_interval(days => 2) from public.machines where machine_id = $$EV-DC-01$$ and not exists (select 1 from public.alarms where alarm_code = $$ERR-CABLE-01$$);

insert into public.alarms (machine_id, alarm_code, description, cause, status, created_at) select id, $$ERR-MODULE-OVERHEAT$$, $$Power module overheated above 85 degrees Celsius$$, $$Module cooling fan failed and cabinet air is too hot$$, $$In Progress$$, now() - make_interval(hours => 30) from public.machines where machine_id = $$EV-DC-01$$ and not exists (select 1 from public.alarms where alarm_code = $$ERR-MODULE-OVERHEAT$$);

insert into public.alarms (machine_id, alarm_code, description, cause, status, created_at) select id, $$ERR-INSULATOR-02$$, $$Insulation resistance below 100 kOhm$$, $$HV insulator set 2 is damaged from moisture$$, $$Open$$, now() - make_interval(days => 3) from public.machines where machine_id = $$EV-DC-04$$ and not exists (select 1 from public.alarms where alarm_code = $$ERR-INSULATOR-02$$);

insert into public.alarms (machine_id, alarm_code, description, cause, status, created_at) select id, $$ERR-COMM-03$$, $$Lost connection to OCPP backend, heartbeat missing 5 min$$, $$Fiber uplink loose at distribution cabinet$$, $$In Progress$$, now() - make_interval(days => 1) from public.machines where machine_id = $$EV-DC-06$$ and not exists (select 1 from public.alarms where alarm_code = $$ERR-COMM-03$$);

insert into public.alarms (machine_id, alarm_code, description, cause, status, created_at) select id, $$ERR-GROUND-FAULT$$, $$Ground fault detected, power cut for safety$$, $$PE ground wire loose at terminal block$$, $$Closed$$, now() - make_interval(days => 5) from public.machines where machine_id = $$EV-AC-03$$ and not exists (select 1 from public.alarms where alarm_code = $$ERR-GROUND-FAULT$$);
